version: '3.8'

services:
  frontend:
    image: zay-ecommerce-frontend:latest
    ports:
      - "3001:3001"
    depends_on:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  backend:
    image: zay-ecommerce-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://youruser:yourpassword@db:5432/yourdatabase
    depends_on:
      - db
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

volumes:
  db-data:
