version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://youruser:yourpassword@db:5432/yourdatabase
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase

volumes:
  db-data:
